#############33 procedures
CREATE TABLE ep(
id INT PRIMARY KEY,
name VARCHAR(50),
department VARCHAR(50),
salary INT,
city VARCHAR(50)
);

INSERT INTO ep VALUES
(1,'Thamkin','IT',50000,'Bangalore'),
(2,'Rahul','HR',40000,'Hyderabad'),
(3,'Priya','IT',60000,'Chennai'),
(4,'Anu','Finance',55000,'Mumbai'),
(5,'Ravi','IT',70000,'Pune');
select * from ep;

DELIMITER //
CREATE procedure show_names1()
BEGIN
SELECT NAME FROM EP;
END //
DELIMITER ;

DELIMITER //
CREATE procedure EP_TABLE()
BEGIN
SELECT * FROM EP;
END //
DELIMITER ;

DELIMITER //
CREATE procedure M_SALARY()
BEGIN
SELECT MAX(SALARY) FROM EP;
END //
DELIMITER ;
CALL M_SALARY;

DELIMITER //
CREATE procedure C_SALARY()
BEGIN
SELECT count(*) FROM EP;
END //
DELIMITER ;
CALL C_SALARY;

DELIMITER //

CREATE TRIGGER emp_insert
AFTER INSERT
ON emp
FOR EACH ROW
BEGIN
    INSERT INTO emp_log
    VALUES('New Employee Added');
END //
DELIMITER ;

DELIMITER //

CREATE TRIGGER emp_update
AFTER UPDATE
ON emp
FOR EACH ROW
BEGIN
    INSERT INTO emp_log
    VALUES('Employee Updated');
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER emp_delete
AFTER DELETE
ON emp
FOR EACH ROW
BEGIN
    INSERT INTO emp_log
    VALUES('Employee Deleted');
END // 
DELIMITER // 


###########TRIGGER
CREATE TRIGGER emp_insert2
AFTER INSERT ON emp
FOR EACH ROW
BEGIN
   INSERT INTO log
   VALUES('Employee Added');
END;

SHOW TRIGGERS;

DELIMITER //

CREATE TRIGGER emp_insert3
AFTER INSERT ON emp
FOR EACH ROW
BEGIN
    INSERT INTO log
    VALUES('Employee Added');
END //

DELIMITER ;
SHOW TRIGGERS;
DELIMITER // 
create trigger emp_log
after delete on emp
FOR EACH ROW
begin
insert into log values("Employee deleted");
end //
DELIMITER ;
SHOW TRIGGERS;

DELIMITER //
CREATE TRIGGER EMP_UPDATE1
AFTER UPDATE ON EMP
FOR EACH ROW
BEGIN
INSERT INTO LOG VALUES("Employee updated");
END //
DELIMITER ;
SHOW TRIGGERS;

DELIMITER //
CREATE TRIGGER EMP_VALUES
AFTER INSERT ON EMP10
FOR EACH ROW
BEGIN
INSERT INTO LOG VALUES("EMPOLYEE INSERTED");
END //
DELIMITER ;
SHOW TRIGGERS;

DELIMITER //
CREATE TRIGGER EMP_UPDATE
AFTER UPDATE ON EMP10
FOR EACH ROW
BEGIN 
INSERT INTO LOG VALUES("EMPLOYEE UPDATED");
END //
DELIMITER ;
SHOW TRIGGERS;

DELIMITER //
CREATE TRIGGER EMP_DELETE1
AFTER DELETE ON EMP10
FOR EACH ROW
BEGIN
INSERT INTO LOG VALUES("EMPLOYEEE DELETED");
END //
DELIMITER ;
SHOW TRIGGERS;



DELIMITER //
CREATE PROCEDURE CHECK_AGE()
BEGIN 
DECLARE AGE INT;
SET AGE = 20;
IF AGE >= 18 THEN
SELECT "ELIGIBLE";
ELSE
SELECT "NOT ELIGIBLE";
END IF ;
END //
DELIMITER ;
DELIMITER //

CREATE PROCEDURE check_age()
BEGIN

DECLARE age INT;

SET age = 20;

IF age >= 18 THEN
   SELECT "ELIGIBLE";
ELSE
   SELECT "NOT ELIGIBLE";
END IF;

END //

DELIMITER ;


SELECT name,
CASE
   WHEN salary >= 50000 THEN 'High Salary'
   WHEN salary >= 30000 THEN 'Medium Salary'
   ELSE 'Low Salary'
END AS salary_status
FROM emp;

CREATE TABLE EMP16 (
    ID INT,
    NAME VARCHAR(50),
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);
DELIMITER //
CREATE procedure SHOW_EMP()
BEGIN 
SELECT * FROM EMP16;
END //
DELIMITER ;
CALL SHOW_EMP();

DELIMITER //
CREATE PROCEDURE SHOW_NAMES6()
BEGIN
SELECT NAME FROM EMP16;
END //
DELIMITER ;
CALL SHOW_NAMES6();

DELIMITER //
CREATE PROCEDURE HIGH_SALARY1()
BEGIN
SELECT * FROM EMP16 WHERE SALARY > 50000;
END //
DELIMITER ;
CALL HIGH_SALARY1();



DELIMITER //
CREATE TRIGGER EMP_INSERT
AFTER INSERT ON emp
FOR EACH ROW
BEGIN
INSERT INTO LOG
VALUES("EMPLOYEE INSERTED");
END // 
DELIMITER ;

DELIMITER //
CREATE procedure DEMO1()
BEGIN
DECLARE SALARY INT;
SET SALARY = 50000;
SELECT SALARY ;
END //
DELIMITER ;
CALL DEMO();


DELIMITER //
CREATE PROCEDURE ADD_NUMBERS()
BEGIN
DECLARE A INT ;
DECLARE B INT ;
SET A = 10;
SET B = 20;
SELECT A + B AS TOTAL;
END //
DELIMITER ;
CALL ADD_NUMBERS();


DELIMITER //
CREATE PROCEDURE SUM_VALUES()
BEGIN
DECLARE A INT;
DECLARE B INT;
SET A = 50;
SET B = 100;
SELECT A + B AS TOTALADD;
END //
DELIMITER ;
CALL SUM_VALUES();

######################## if with procedurers
DELIMITER // 
CREATE PROCEDURE CHECK_AGE1()
BEGIN
DECLARE AGE INT;
SET AGE = 20;
IF AGE >= 18 THEN
SELECT "ELIGIBLE";
ELSE 
SELECT "NOT ELIGIBLE";
END IF;
END //
DELIMITER ;
CALL CHECK_AGE1();

DELIMITER //
CREATE PROCEDURE CHECK_SALARY()
BEGIN 
DECLARE SALARY INT ;
SET SALARY = 60000;
IF SALARY > 50000 THEN
SELECT "HIGH SALARY";
ELSE
SELECT "LOW SALARY";
END IF;
END //
DELIMITER ;
CALL CHECK_SALARY();

DELIMITER //
CREATE PROCEDURE CHECK_MARKS()
BEGIN 
DECLARE MARKS INT;
SET MARKS = 80;
IF MARKS >= 35 THEN SELECT "PASS";
ELSE 
SELECT "FAIL";
END IF;
END //
DELIMITER ;
CALL CHECK_MARKS();
DELIMITER ;
CALL CHECK_MARKS();



DELIMITER //
CREATE PROCEDURE GRADE_CHECK()
BEGIN
DECLARE MARKS INT;
SET MARKS = 85;
IF MARKS >= 75 THEN SELECT 'A GRADE';
ELSEIF MARKS >= 35 THEN SELECT "PASS";
ELSE 
SELECT "FAIL";
END IF ;
END // 
 DELIMITER ;
 

DELIMITER //
CREATE PROCEDURE GRADE_CHECK2()
BEGIN
DECLARE MARKS INT;
SET MARKS = 85;
IF MARKS >= 90 THEN SELECT "A GRADE";
ELSEIF MARKS >= 75 THEN SELECT "B GRADE";
ELSEIF MARKS >= 50 THEN SELECT "C GRADE";
ELSE SELECT "FAIL";
END IF;
END //
DELIMITER ;
CALL GRADE_CHECK2();

DELIMITER //
CREATE PROCEDURE AGE_CHECK()
BEGIN 
DECLARE AGE INT; 
SET AGE = 22;
IF AGE >= 25 THEN SELECT "EXPERIENCED";
ELSEIF AGE >= 18 THEN SELECT "ELIGIBLE";
ELSE SELECT "NOT ELIGIBLE";
END IF;
END //
DELIMITER ;
CALL AGE_CHECK();

DELIMITER //
CREATE PROCEDURE CHECK_MARKS1() 
BEGIN
DECLARE MARKS INT;
SET MARKS = 90;
IF MARKS >= 90 THEN SELECT "A GRADE";
ELSEIF MARKS >= 75 THEN SELECT "B GRADE";
ELSE SELECT "C GRADE";
END IF;
END //
DELIMITER ;
CALL CHECK_MARKS1();

# IN PARAMETER
DELIMITER //
CREATE PROCEDURE GET_BONUS(OUT BONUS  INT)
BEGIN
SET BONUS = 10000;
END //
DELIMITER ;
CALL GET_BONUS(@B);
SELECT @B;

DELIMITER //
CREATE PROCEDURE GET_STATUS(OUT status varchar(20))
BEGIN
SET STATUS ="ACTIVE";
END //
DELIMITER ;
call get_status(@s);
select @s;

DELIMITER //
CREATE PROCEDURE SHOW_NAME( IN EMP_NAME VARCHAR(50))
BEGIN 
SELECT EMP_NAME;
END //
DELIMITER ; 


DELIMITER //
CREATE PROCEDURE SHOW_NAME1(
IN EMP_NAME VARCHAR(50))
BEGIN

SELECT EMP_NAME;

END //

DELIMITER ;
CALL SHOW_CITY('BANGALORE');

DELIMITER //
CREATE PROCEDURE SHOW_NAME1(
IN EMP_NAME VARCHAR(50)
)
BEGIN
SELECT EMP_NAME;
END //
DELIMITER ;


DELIMITER //

CREATE PROCEDURE SHOW_NAME(
IN EMP_NAME VARCHAR(50)
)
BEGIN
    SELECT EMP_NAME;
END //

DELIMITER ;

CALL SHOW_NAME('THAMKIN');


DELIMITER //
CREATE PROCEDURE SHOW_NAME( IN EMP_NAME VARCHAR(50))
BEGIN SELECT EMP_NAME;
END //
DELIMITER ;
CALL SHOW_NAME('THAMKIN');
